const frases = [
    'É hora de esquecer os erros do passado e começar a planejar os erros do futuro.',
    'Alguns relacionamentos são como uma partida de futebol, Em certas ocasiões aparece um melhor para lhe substituir',
    'Como é que pode no “memo” dia o cara ser assaltado, sequestrado, assassinado e ainda acabar a gasolina do carro? ',
    'Bebel, nós estamos brigando negócio de dinheiro, dinheiro é coisa material, o importante é que nós estamos bem, estamos com saúde.',
    'Lineu, gostaria de agradecer você a essa crítica que você ai, extremamente destrutiva, realmente ajudou muito a levantar minha moral. Obrigado. ',
    'Beiçola me vê dois pasteis de carne aí e bota na conta do seu floriano',
    'Este arcondicionado é a garantia do meu casamento',
    'Bebel, não vamo polemizar',
    'Olha, Lineu, oportunidade não bate duas vezes na mesma porta. confia em mim!',
    'Senti uma catinga achei que era o seu Floriano não falei nada pq não queria ofender né',
    '"MEU quarto"? ta dizendo isso só porque a casa é do SEU pai??',
    'Maria Isabel, tu já fez duas perguntas, eu ainda não fiz nenhuma',
    'com esse calor danado aqui a bebel não me da nem bom dia',
    'Izabel não tem nada a ver com pirâmide isso aí eh uma coisa chamada Jantar da Fortuna pelo amor de deus',
    'Lineu você está insinuando que eu me aproveito de você?',
    'seu Floriano... o senhor tem... 100 reais pra me emprestar??',
    'Lineu!!! finalmente um homem de VISÃO nessa casa!',
    'Carrara Taxi, ou Taxi Carrara a gnt ainda não decidiu ainda',
    'a dona nenê a senhora pra mim é a pessoa mais especial que tem eu jamais botaria a senhora num esquema furado to botando num esquema que eu sei que da certo',
    'VOU EMBORA DAQUI MARIA IZABEL',
    'culpa MINHA?!! eu fiz dentro da honestidade denda LEI! eu não fiz nada de errado!',
    'sim a senhora esta pagando o taxi mas não é a minha dona',
    'devemos deixar de ser egoístas e começar a pensar em nós mesmos',
    'antes de você... esculhambar... deixa eu falar duas outras coisas que eu gostaria de colocar aí pra toda família...',
    'ô Lineu, você acha que eu ia deixar você numa fria rapaz?',
    'seu Floriano... o senhor tem... 100 reais pra me emprestar??',
    'devemos deixar de ser egoístas e começar a pensar em nós mesmos',
    'o responsável é o PM, que ao invés de estar policiando, estava aqui, dentro da casa de sua mãe, paquerando a minha mulher',
    'tu não vê vaca dizer "ó o leite vai durar até tal dia"',
    'é assim, Maria Isabel, o dinheiro faz muita loucura com a cabeça de uma pessoa normal, imagine o que que não vai fazer com a cabeça de uma pessoa como o Tuco',
    'pra rico tempo eh dinheiro né, ou melhor.. tempo é money pq eles pensa tudo em dolar',
    'eu prometo... criar a sociedade... a amparar... o pobre e formatar leis!!',
    'bebel, não vou falar grosso com voce, entao vou falar fino:ᶜᵒʳᵗᵃ ᵐᵉᵘ ᶜᵃᵇᵉˡᵒ?',
    'já chega a carga tributária que o pequeno empresario tem que arcar aqui',
    'lineu.... é uma PA RA DA que nós vamos ganhar uma BA BA',
    'já tirou a janta? vou ali matar uma pessoa e já volto',
    'meu sogro aqui que é sangue do meu sangue',
    'EU? isso é calunia sua eu nunca fiz isso',
    'a solidão da pessoa que chegou lá, que obteve o que ela queria, é muito grande ',
    'olha, Lineu, oportunidade não bate duas vezes na mesma porta. confia em mim!',
    'é... é muito simples... voce entra como entrada. ta aí voce arruma duas pessoas essa pessoas entra como entrada e você vira salada as pessoas arrumam outras duas pessoas você vira prato principal',
    'Lineu eu já fiz tudo, ta na hora de você fazer alguma coisa',
    'errar é humano, colocar a culpa em alguém é estratégico',
    'como é que pegou fogo no quarto do tuco e seu floriano, se geralmente o lugar que PEGA FOGO é onde temos o quarto meu e da bebel?',
    'eu acredito em um amanhã melhor, até porque amanhã é sexta-feira',
    'dona nenê ta tudo armado ta tudo tranquilo a senhora tá na cara do gol... é só chutar. fica tranquila',
    'eu tambem to muito orgulhosa Maria Izabel',
    'quem manda eu querer o melhor pra minha esposa, que NO CASO é sua filha',
    'Lineu você está insinuando que eu me aproveito de você?',
    'trambolho? ô beiçola que trambolho o meu carro tem um pouco de idade aí mas ta bom tem que fazer uma coisinha ou outra aí mas ta melhor que muito carro de muita gente que anda aí na praça'

]

module.exports = frases;